name: "Export Game"
description: "Exports Godot project for multiple platforms"
inputs:
  godot_version:
    description: "Godot version to use"
    required: true
  relative_project_path:
    description: "Path to the Godot project"
    required: true
  export_path:
    description: "Path where to export the game"
    required: true
  export_format:
    description: "Export format (Linux/Windows Desktop/macOS/HTML5)"
    required: true
  export_name:
    description: "Name of the exported file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Export Templates
      shell: sh
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates/
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

    - name: Setup Project
      shell: sh
      run: |
        mkdir -p .godot/editor/
        chmod -R 777 .godot
        cp -r ${{ inputs.relative_project_path }}/* ./
        chmod 666 export_presets.cfg || true

    - name: Export Project
      shell: sh
      run: |
        mkdir -v -p ${{ inputs.export_path }}

        # Determine file extension based on export format
        FILE_EXT=""
        case "${{ inputs.export_format }}" in
          "Linux") FILE_EXT="x86_64" ;;
          "Windows Desktop") FILE_EXT="exe" ;;
          "macOS") FILE_EXT="zip" ;;
          "HTML5") FILE_EXT="html" ;;
        esac

        # Export the project
        godot --headless --verbose \
          --export-release "${{ inputs.export_format }}" \
          "${{ inputs.export_path }}/${{ inputs.export_name }}.$FILE_EXT"
