name: "Export Game"
description: "Exports a Godot project"
inputs:
  godot_version:
    description: "Godot version to use"
    required: true
  relative_project_path:
    description: "Path to the Godot project"
    required: true
  export_path:
    description: "Path where to export the game"
    required: true
  export_format:
    description: "Export format (win64, x11.64, etc)"
    required: true

steps:
  # Add this step before the export
  - name: Create logs directory
    shell: bash
    run: mkdir -p .godot/logs

runs:
  using: "composite"
  steps:
    - name: Download Godot
      shell: bash
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/${{ inputs.godot_version }}-stable/Godot_v${{ inputs.godot_version }}-stable_linux.x86_64.zip
        unzip Godot_v${{ inputs.godot_version }}-stable_linux.x86_64.zip
        mv Godot_v${{ inputs.godot_version }}-stable_linux.x86_64 godot
        chmod +x godot

    - name: Setup export templates
      shell: bash
      run: |
        mkdir -p ~/.local/share/godot/export_templates/4.3.stable
        unzip ./templates/templates.tpz
        mv templates/* ~/.local/share/godot/export_templates/4.3.stable/

    - name: Setup project
      shell: bash
      run: |
        mkdir -p .godot/editor/
        chmod -R 777 .godot
        cp -r src/* ./
        chmod 666 export_presets.cfg
        echo "Project setup complete. Contents:"
        ls -la
        echo "export_presets.cfg contents:"
        cat export_presets.cfg

    - name: Export project
      shell: bash
      run: |
        echo "Starting export process..."
        echo "Current directory: $(pwd)"
        echo "Project path: ${{ inputs.relative_project_path }}"
        echo "Export path: ${{ inputs.export_path }}"
        echo "Export format: ${{ inputs.export_format }}"

        mkdir -p ${{ inputs.export_path }}

        ./godot --headless --verbose --path ${{ inputs.relative_project_path }} --export-release "${{ inputs.export_format }}" "${{ inputs.export_path }}/game" || \
        ./godot --headless --verbose --path ${{ inputs.relative_project_path }} --export "${{ inputs.export_format }}" "${{ inputs.export_path }}/game"

        export_status=$?
        if [ $export_status -ne 0 ]; then
          echo "Export failed with status $export_status"
          if [ -d ".godot/logs" ]; then
            echo "Contents of log directory:"
            ls -la .godot/logs/
          fi
        fi
        exit $export_status
