name: "CI"
on:
  push:
    branches: [main, master]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "README.md"

env:
  GODOT_VERSION: 4.3
  WINDOWS_EXPORT_NAME: windows
  LINUX_EXPORT_NAME: linux
  MAC_EXPORT_NAME: mac
  PROJECT_PATH: src

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$WINDOWS_EXPORT_NAME.exe"

      - name: Upload Artifact
        uses: actions/upload-artifact@4
        with:
          name: windows
          path: build/windows
          retention-days: 5

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$LINUX_EXPORT_NAME.x86_64"

      - name: Upload Artifact
        uses: actions/upload-artifact@4
        with:
          name: linux
          path: build/linux
          retention-days: 5

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@3
        with:
          path: build/web

  deploy-web:
    needs: export-web
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@4

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/$MAC_EXPORT_NAME.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@4
        with:
          name: mac
          path: build/mac
          retention-days: 5

  create-release:
    name: Create Release
    needs: [export-windows, export-linux, export-mac, export-web, deploy-web]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@4
        with:
          name: windows
          path: build/windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@4
        with:
          name: linux
          path: build/linux

      - name: Download Mac Artifact
        uses: actions/download-artifact@4
        with:
          name: mac
          path: build/mac

      - name: Create Release
        uses: softprops/action-gh-release@2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Build-Version-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            build/windows/${{ env.WINDOWS_EXPORT_NAME }}.exe
            build/linux/${{ env.LINUX_EXPORT_NAME }}.x86_64
            build/mac/${{ env.MAC_EXPORT_NAME }}.zip
          fail_on_unmatched_files: true
          body: |
            Commit Description:
            ${{ github.event.head_commit.message }}


            Build generated from commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Timestamp: ${{ github.event.head_commit.timestamp }}
