name: Build on Push
run-name: Building version ${{ github.run_number }}
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  #schedule:
  #- cron: '0 0 * * *'  # Added scheduled nightly builds

jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Import assets
        run: |
          godot --headless --verbose --export-release
        shell: sh
  build:
    needs: import-assets
    runs-on: ubuntu-latest # All builds now use ubuntu-latest
    container: barichello/godot-ci:4.3 # Using container for all platforms
    strategy:
      matrix:
        platform: [linux, windows, macos, web]
        include:
          - platform: linux
            export_folder: bin/Linux
            export_format: "Linux"
            file_extension: x86_64 # Add this
          - platform: windows
            export_folder: bin/Windows
            export_format: "Windows Desktop"
            file_extension: exe
          - platform: macos
            export_folder: bin/MacOS
            export_format: "macOS"
            file_extension: zip
          - platform: web
            export_folder: bin/Web
            export_format: "HTML5"
            file_extension: html
      fail-fast: false
      # Continue with other platforms if one fails

    permissions: write-all

    env:
      GODOT_VERSION: 4.3
      GODOT_PROJECT_LOCATION: src
      APPLICATION_NAME: Deans_2D_Projects
      BUILD_NAME: Deans_2D_Projects-${{ matrix.platform }}-nightly-${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          # Remove lfs: true | not needed

      # Special handling for web platform
      - name: Setup export templates
        if: steps.cache-templates.outputs.cache-hit != 'true' && matrix.platform != 'web'
        run: |
          apt-get update && apt-get install -y curl
          mkdir -p ./templates
          curl -L -o ./templates/templates.tpz "https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz"

          echo "Downloaded template archive:"
          ls -la ./templates/templates.tpz
        shell: sh

      - name: Cache Godot templates
        if: matrix.platform != 'web' # Skip for web as it uses container
        id: cache-templates
        uses: actions/cache@v4.2.0
        with:
          path: ./templates
          key: godot-templates-${{ env.GODOT_VERSION }}

      - name: Create export directory
        run: mkdir -p ${{ matrix.export_folder }}

      # Different export process for web
      - name: Export Game
        uses: ./.github/workflows/actions
        id: export
        with:
          godot_version: ${{ env.GODOT_VERSION }}
          relative_project_path: ${{ env.GODOT_PROJECT_LOCATION }}
          export_path: ${{ matrix.export_folder }}
          export_format: ${{ matrix.export_format }}
          export_name: ${{ env.APPLICATION_NAME }}
        continue-on-error: true

      - name: Check export results
        run: |
          echo "Export folder contents:"
          ls -la ${{ matrix.export_folder }}
          if [ -z "$(ls -A ${{ matrix.export_folder }})" ]; then
            echo "Error: Export folder is empty!"
            exit 1
          fi
        shell: sh

      # Deploy web build to GitHub Pages
      - name: Deploy to GitHub Pages
        if: matrix.platform == 'web' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ matrix.export_folder }}
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success() && matrix.platform != 'web'
        id: create_release
        uses: softprops/action-gh-release@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          draft: false
          prerelease: true
          files: |
            ${{ env.BUILD_NAME }}.${{ matrix.file_extension }}
          fail_on_unmatched_files: true
          body: |
            Build generated from commit: ${{ github.sha }}
            Commit Title: ${{ github.event.head_commit.message }}
            Commit Description:
            ${{ github.event.head_commit.description || 'No description provided' }}
            Branch: ${{ github.ref_name }}
            Timestamp: ${{ github.event.head_commit.timestamp }}

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ env.BUILD_NAME }}
          path: ${{ matrix.export_folder }}
          retention-days: 7
          if-no-files-found: error
